services:
  postgres-s3-restore:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname=$DATABASE_URL"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"